name = "dpm-transition"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[ai]
binding = "AI"

[vars]
MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"

[observability]
enabled = true
